/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Chapter = IDL.Record({
  'direction' : IDL.Text,
  'text' : IDL.Text,
  'streetName1' : IDL.Text,
  'streetName2' : IDL.Text,
  'choiceIndex' : IDL.Nat,
});
export const GpsCoord = IDL.Record({
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
});
export const Run = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'userName' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'userId' : IDL.Principal,
  'slug' : IDL.Text,
  'genre' : IDL.Text,
  'chapters' : IDL.Vec(Chapter),
  'totalDistance' : IDL.Float64,
  'gpsRoute' : IDL.Vec(GpsCoord),
  'choices' : IDL.Vec(IDL.Text),
});
export const SaveRunRequest = IDL.Record({
  'startTime' : IDL.Int,
  'userName' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'genre' : IDL.Text,
  'chapters' : IDL.Vec(Chapter),
  'totalDistance' : IDL.Float64,
  'gpsRoute' : IDL.Vec(GpsCoord),
  'choices' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllRuns' : IDL.Func([], [IDL.Vec(Run)], ['query']),
  'getMyRuns' : IDL.Func([], [IDL.Vec(Run)], ['query']),
  'getRunBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Run)], ['query']),
  'getRunsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Run)], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'saveRun' : IDL.Func([SaveRunRequest], [IDL.Text], []),
  'setUserName' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Chapter = IDL.Record({
    'direction' : IDL.Text,
    'text' : IDL.Text,
    'streetName1' : IDL.Text,
    'streetName2' : IDL.Text,
    'choiceIndex' : IDL.Nat,
  });
  const GpsCoord = IDL.Record({ 'lat' : IDL.Float64, 'lon' : IDL.Float64 });
  const Run = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'userName' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'userId' : IDL.Principal,
    'slug' : IDL.Text,
    'genre' : IDL.Text,
    'chapters' : IDL.Vec(Chapter),
    'totalDistance' : IDL.Float64,
    'gpsRoute' : IDL.Vec(GpsCoord),
    'choices' : IDL.Vec(IDL.Text),
  });
  const SaveRunRequest = IDL.Record({
    'startTime' : IDL.Int,
    'userName' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'genre' : IDL.Text,
    'chapters' : IDL.Vec(Chapter),
    'totalDistance' : IDL.Float64,
    'gpsRoute' : IDL.Vec(GpsCoord),
    'choices' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllRuns' : IDL.Func([], [IDL.Vec(Run)], ['query']),
    'getMyRuns' : IDL.Func([], [IDL.Vec(Run)], ['query']),
    'getRunBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Run)], ['query']),
    'getRunsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Run)], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
    'saveRun' : IDL.Func([SaveRunRequest], [IDL.Text], []),
    'setUserName' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };