/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'direction' : string,
  'text' : string,
  'streetName1' : string,
  'streetName2' : string,
  'choiceIndex' : bigint,
}
export interface GpsCoord { 'lat' : number, 'lon' : number }
export interface Run {
  'id' : bigint,
  'startTime' : bigint,
  'userName' : [] | [string],
  'title' : string,
  'endTime' : bigint,
  'userId' : Principal,
  'slug' : string,
  'genre' : string,
  'chapters' : Array<Chapter>,
  'totalDistance' : number,
  'gpsRoute' : Array<GpsCoord>,
  'choices' : Array<string>,
}
export interface SaveRunRequest {
  'startTime' : bigint,
  'userName' : [] | [string],
  'title' : string,
  'endTime' : bigint,
  'genre' : string,
  'chapters' : Array<Chapter>,
  'totalDistance' : number,
  'gpsRoute' : Array<GpsCoord>,
  'choices' : Array<string>,
}
export interface _SERVICE {
  'getAllRuns' : ActorMethod<[], Array<Run>>,
  'getMyRuns' : ActorMethod<[], Array<Run>>,
  'getRunBySlug' : ActorMethod<[string], [] | [Run]>,
  'getRunsByUser' : ActorMethod<[Principal], Array<Run>>,
  'getUser' : ActorMethod<[Principal], [] | [string]>,
  'saveRun' : ActorMethod<[SaveRunRequest], string>,
  'setUserName' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];