/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SaveRunRequest {
    startTime: bigint;
    userName?: string;
    title: string;
    endTime: bigint;
    genre: string;
    chapters: Array<Chapter>;
    totalDistance: number;
    gpsRoute: Array<GpsCoord>;
    choices: Array<string>;
}
export interface Run {
    id: bigint;
    startTime: bigint;
    userName?: string;
    title: string;
    endTime: bigint;
    userId: Principal;
    slug: string;
    genre: string;
    chapters: Array<Chapter>;
    totalDistance: number;
    gpsRoute: Array<GpsCoord>;
    choices: Array<string>;
}
export interface Chapter {
    direction: string;
    text: string;
    streetName1: string;
    streetName2: string;
    choiceIndex: bigint;
}
export interface GpsCoord {
    lat: number;
    lon: number;
}
export interface backendInterface {
    getAllRuns(): Promise<Array<Run>>;
    getMyRuns(): Promise<Array<Run>>;
    getRunBySlug(slug: string): Promise<Run | null>;
    getRunsByUser(userId: Principal): Promise<Array<Run>>;
    getUser(userId: Principal): Promise<string | null>;
    saveRun(req: SaveRunRequest): Promise<string>;
    setUserName(name: string): Promise<void>;
}
import type { Chapter as _Chapter, GpsCoord as _GpsCoord, Run as _Run, SaveRunRequest as _SaveRunRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllRuns(): Promise<Array<Run>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRuns();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRuns();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRuns(): Promise<Array<Run>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRuns();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRuns();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRunBySlug(arg0: string): Promise<Run | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRunBySlug(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRunBySlug(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRunsByUser(arg0: Principal): Promise<Array<Run>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRunsByUser(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRunsByUser(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveRun(arg0: SaveRunRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRun(to_candid_SaveRunRequest_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRun(to_candid_SaveRunRequest_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setUserName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserName(arg0);
            return result;
        }
    }
}
function from_candid_Run_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Run): Run {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Run]): Run | null {
    return value.length === 0 ? null : from_candid_Run_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    userName: [] | [string];
    title: string;
    endTime: bigint;
    userId: Principal;
    slug: string;
    genre: string;
    chapters: Array<_Chapter>;
    totalDistance: number;
    gpsRoute: Array<_GpsCoord>;
    choices: Array<string>;
}): {
    id: bigint;
    startTime: bigint;
    userName?: string;
    title: string;
    endTime: bigint;
    userId: Principal;
    slug: string;
    genre: string;
    chapters: Array<Chapter>;
    totalDistance: number;
    gpsRoute: Array<GpsCoord>;
    choices: Array<string>;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        userName: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.userName)),
        title: value.title,
        endTime: value.endTime,
        userId: value.userId,
        slug: value.slug,
        genre: value.genre,
        chapters: value.chapters,
        totalDistance: value.totalDistance,
        gpsRoute: value.gpsRoute,
        choices: value.choices
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Run>): Array<Run> {
    return value.map((x)=>from_candid_Run_n2(_uploadFile, _downloadFile, x));
}
function to_candid_SaveRunRequest_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveRunRequest): _SaveRunRequest {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    userName?: string;
    title: string;
    endTime: bigint;
    genre: string;
    chapters: Array<Chapter>;
    totalDistance: number;
    gpsRoute: Array<GpsCoord>;
    choices: Array<string>;
}): {
    startTime: bigint;
    userName: [] | [string];
    title: string;
    endTime: bigint;
    genre: string;
    chapters: Array<_Chapter>;
    totalDistance: number;
    gpsRoute: Array<_GpsCoord>;
    choices: Array<string>;
} {
    return {
        startTime: value.startTime,
        userName: value.userName ? candid_some(value.userName) : candid_none(),
        title: value.title,
        endTime: value.endTime,
        genre: value.genre,
        chapters: value.chapters,
        totalDistance: value.totalDistance,
        gpsRoute: value.gpsRoute,
        choices: value.choices
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
